baseurl: "/lq-tennis/"
permalink: "pretty"
title: "Lake Quivira Tennis Association"

logo:
  mobile: "images/logo/logo-mobile.svg" 
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "128px"
  desktop_width: "260px"

home: 
  limit_sections: 6

collections:
  events:
    output: true
    sort_by: "weight"
  leagues:
    output: true
    sort_by: "weight"
  sections:
    output: true
    sort_by: "weight"
  teams:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "events"
  - scope:
      path: ""
      type: "leagues"
    values:
      layout: "leagues"
  - scope:
      path: ""
      type: "teams"
    values:
      layout: "teams"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
